stages:
  syllabify:
    cmd: ./lexicon/syllabify.sh lexicon/tsrjh.txt > lexicon/tsrjh.wli
  to-ph:
    cmd: lexurgy sc lexicon/tsrjh.lsc lexicon/tsrjh.wli -o phon
    deps:
    - lexicon/syllabify.sh
    - lexicon/tsrjh.txt
    - lexicon/tsrjh.lsc
    - lexicon/tsrjh.wli
    outs:
    - lexicon/tsrjh_phon.wlm
    - lexicon/tsrjh_phon.wli
