stages:
  syllabify:
    cmd: ./lexicon/syllabify.sh lexicon/tsrjh.txt > lexicon/tsrjh.wli
  to-ph:
    cmd: lexurgy sc lexicon/tsrjh.lsc lexicon/tsrjh.wli
    deps:
    - lexicon/tsrjh.lsc
    - lexicon/tsrjh.wli
    outs:
    - lexicon/tsrjh_ev.wlm
    - lexicon/tsrjh_ev.wli
